online-store/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/currentuser' => 'users#current_user'
  get '/auth/facebook/callback' => 'sessions#create'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :items, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :items, only: [:show] do 
    post '/purchase' => 'transactions#create'
    resources :comments, only: [:new, :create, :index, :show]
  end
end

online-store/app/models/item.rb
class Item < ApplicationRecord
    # model relationships
    has_many :transactions
    has_many :users, through: :transactions

    validates_presence_of :title, allow_blank: false 
    validates_presence_of :cost, allow_blank: false
    validates_presence_of :stock, allow_blank: false
    validates :cost, :numericality => {:greater_than => 0}
end

online-store/app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :admin_only, except: [:index, :show]
    def new 
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        if @item.valid?
            @item.save
            render json: @item
        else
            render 'items/new'
        end
    end

    def edit
        @item = Item.find(params[:id])
    end 

    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to item_path(@item)
    end

    def index
        @items = Item.all
        respond_to do |format|
            format.html { render :index }
            format.json { render json: @items}
        end
    end

    def show
        @item = Item.find(params[:id])
        @transaction = Transaction.new
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @item}
        end
    end

    def destroy
        @item = Item.find(params[:id])
        @item.delete
        redirect_to items_path
    end

    private 

    def item_params
        params.require(:item).permit(:title, :description, :cost, :stock, :image_url)
    end
end

online-store/app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
<% if item.errors.any? %>
<div id="error_explanation">
    <h2>There was an error: </h2>
    <ul>
      <% item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field <%= ' field_with_errors' if item.errors[:title].any? %>">
    <%= f.label :title %> <br>
    <%= f.text_field :title, class: :input %> 
</div>
<br><br>
<div class="field <%= ' field_with_errors' if item.errors[:description].any? %>">
    <%= f.label :description %> <br>
    <%= f.text_field :description, class: :input %> 
</div>
<br><br>
<div class="field <%= ' field_with_errors' if item.errors[:cost].any? %>">
    <%= f.label :cost %> <br>
    <%= f.number_field :cost, step: :any, class: :input %> 
</div>
<br><br>
<div class="field <%= ' field_with_errors' if item.errors[:stock].any? %>">
    <%= f.label :stock %> <br>
    <%= f.number_field :stock, step: 1, class: :input %> 
</div>
<br><br>
    <%= f.label :image_url %> <br>
    <%= f.text_field :image_url, class: :input %> <br> <br>
   
    <% if params[:id] %> 
        <%= link_to 'Back', item_path(item), class: "link back" %>
        <%= f.submit 'Update Listing', class: :button %>
        <%= link_to 'Delete Listing', item_path(item), method: :delete, class: "link back" %>
    <% else %>
        <%= link_to 'Back', root_path, class: "link back" %>
        <%= f.submit 'Create New Listing', class: :button %>
    <% end %>
<% end %>

online-store/app/views/items/edit.html.erb
<h1>Edit this item</h1>
<%= render 'form', item: @item %>

online-store/app/views/items/index.html.erb
  <div class="top-div">
    <%= link_to 'Back', root_path, class: "link back" %>
    <% if admin? %>
    <%= link_to 'Create Item Listing', new_item_path, class: "button" %>
    <% end %>
    <br>

    <% @items.each do |item| %>
    <div class = "col-33">
       <div class="item-index">
        <a href=<%= item_path(item)%>> <%= image_tag item.image_url, class: :image, "data-id": item.id %><%= item.title %></a>
       </div>
    </div>
    <% end %>
  </div>

  

online-store/app/views/items/new.html.erb
<h1>Create a new item: </h1>
<%= render 'form', item: @item %>

online-store/app/views/items/show.html.erb
<div class="top-div">
<img class="show-image" src="<%= @item.image_url%>" alt="No available image"></img>
<h1><%= @item.title %></h1>
<h3><%= @item.description %></h3>
<p>$ <%= @item.cost %></p>
<p>Left in stock: <%= @item.stock %></p> 
<% if admin? %>
<%= link_to 'Back', items_path, class: "link back" %>   
    <%= link_to 'Edit this item', edit_item_path(@item), class: :edit %> 
    <%= link_to 'Delete this item', item_path(@item), method: 'delete', class: 'link delete' %>
<% else %>
    <%= form_for(@transaction, url: item_purchase_path(@item)) do |f| %>
        <%= f.label :quantity %>
        <%= f.number_field :quantity, value: 1 %>
        <%= link_to 'Back', items_path, class: "link back" %>  
        <%= f.submit 'Purchase', class: :button %>
    <% end %>
    <br>
    <br>
    <%= link_to 'Create a comment', new_item_comment_path(@item) %> |
    <%= link_to 'View comments', item_comments_path(@item), class: 'comment-link' %>
<% end %>
</div>