online-store/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/currentuser' => 'users#current_user'
  get '/auth/facebook/callback' => 'sessions#create'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :items, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :items, only: [:show] do 
    post '/purchase' => 'transactions#create'
    resources :comments, only: [:new, :create, :index, :show]
  end
end

online-store/app/models/comment.rb
class Comment < ApplicationRecord
end

online-store/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_log_in, except: [:show, :index]
    def new
        @comment = Comment.new
    end

    def create
        @comment = Comment.create(user_id: current_user.id, item_id: params[:item_id], content: params[:comment][:content])
        redirect_to item_comment_path(@comment.item_id,@comment)
    end

    def show
        @comment = Comment.find(params[:id])
        @user = User.find_by(id: @comment.user_id)
        @item = Item.find_by(id: @comment.item_id)
    end

    def index
        @comments = Comment.where(item_id: params[:item_id])
        @item = Item.find_by(id: params[:item_id])
        respond_to do |format|
            format.html { render :index }
            format.json { render json: @comments}
        end
    end

end

online-store/app/views/comments/_form.html.erb
<%= form_for comment, url: item_comments_path(params[:item_id]), method: :post do |f| %>
    <%= f.label :content %> <br>
    <%= f.text_field :content, class: :input %> <br> <br>
    <%= link_to 'Back', item_path(params[:item_id]), class: "link back" %>
    <%= f.submit 'Submit', class: :button %>
<% end %>

online-store/app/views/comments/index.html.erb
<div class="top-div">
<h1>Comments for <%= @item.title %></h1>
<%= link_to 'Back', item_path(@item), class: "link back" %>
<ul>
    <% @comments.each do |comment| %>
    <li><a href= <%= item_comment_path(comment.item_id,comment.id) %>><%= comment.content %></a></li>   
    <% end %>
</ul>
</div>

online-store/app/views/comments/new.html.erb
<div class="top-div">
<h1>Post a comment on this item:</h1>
<%= render 'form', comment: @comment %>
</div>

online-store/app/views/comments/show.html.erb
<div class="top-div">
    <h3><%= @user.name %> posted on <%= @item.title %></p>
        <p><%= @comment.content %></p>
        <%= link_to 'Back', item_path(@comment.item_id), class: "link back" %>
</div>
